#!/bin/bash
# Daily corpus snapshot generator + izabael.com sync — runs at 00:30 UTC.
# Generated by iza-3 for playground-cast Phase 8.
# Extended for Phase 6 (multi-provider-lab): syncs new snapshots to
# izabael-com and redeploys so /research/playground-corpus/ stays live daily.

IZAPLAYER=/home/bastard/Documents/izaplayer
IZABAEL_COM=/home/bastard/Documents/izabael-com
FLYCTL=/home/bastard/.fly/bin/flyctl
CORP_SRC="$IZAPLAYER/agents/corpus/output"
CORP_DEST="$IZABAEL_COM/research/playground-corpus"
LOG="$CORP_SRC/cron.log"

cd "$IZAPLAYER"

{
  echo ""
  echo "[$(date)] === Daily corpus snapshot ==="
  /usr/bin/python3 agents/corpus/generate_corpus.py 2>&1
  echo "[$(date)] === Snapshot done ==="
  echo ""

  # ── Sync to izabael-com ────────────────────────────────────────────
  echo "[$(date)] === Syncing to izabael-com ==="

  # Always update manifest files (index.json + agents.json)
  cp "$CORP_SRC/index.json"  "$CORP_DEST/index.json"  && echo "  ✓ index.json"
  cp "$CORP_SRC/agents.json" "$CORP_DEST/agents.json" && echo "  ✓ agents.json"

  # Copy new daily snapshots (never overwrite existing)
  for f in "$CORP_SRC/daily/"*.json; do
    bn=$(basename "$f")
    if [ ! -f "$CORP_DEST/daily/$bn" ]; then
      cp "$f" "$CORP_DEST/daily/$bn" && echo "  ✓ daily/$bn (new)"
    fi
  done

  # Copy new full snapshots (never overwrite existing)
  for f in "$CORP_SRC/full/"*.json; do
    bn=$(basename "$f")
    if [ ! -f "$CORP_DEST/full/$bn" ]; then
      cp "$f" "$CORP_DEST/full/$bn" && echo "  ✓ full/$bn (new)"
    fi
  done

  # Commit and push izabael-com if anything changed
  cd "$IZABAEL_COM"
  git add research/playground-corpus/
  if git diff --cached --quiet; then
    echo "[$(date)] No new corpus files — skipping commit + deploy"
  else
    DATE=$(date +%Y-%m-%d)
    git commit -m "corpus: daily refresh $DATE

Auto-synced from izaplayer agents/corpus/output/ by corpus_cron_wrapper.sh.
New snapshots pulled daily at 00:30 UTC."
    git push && echo "[$(date)]   ✓ git pushed"

    # Deploy to fly.dev — only runs when there's new data
    echo "[$(date)] Deploying izabael-com..."
    "$FLYCTL" deploy --app izabael --strategy immediate 2>&1 | tail -5
    echo "[$(date)]   ✓ deployed"
  fi

  echo "[$(date)] === Sync done ==="

} >> "$LOG" 2>&1
