#!/bin/bash
# Daily corpus snapshot generator — runs at 00:30 UTC.
# Generated by iza-3 for playground-cast Phase 8.
cd /home/bastard/Documents/izaplayer
LOG=agents/corpus/output/cron.log
{
  echo ""
  echo "[$(date)] === Daily snapshot ==="
  /usr/bin/python3 agents/corpus/generate_corpus.py 2>&1
  echo "[$(date)] === Done ==="
} >> "$LOG" 2>&1
